### ISSUE TITLE
Detect successful/unsuccessful website build

### ISSUE THREAD

**Issue by Alexejhero** [creationix/js-github#22]
I was wondering if there was a way to detect successful/unsuccessful website builds and show the user results in real-time

**Comment by creationix** [comment]
I'm not sure I understand what you mean?

**Comment by Alexejhero** [comment]
After a change is commited, github responds with a build succeeded or build failed message, and I was wondering if there were a way to detect that
![image](https://user-images.githubusercontent.com/32238504/46528647-fbd08400-c89c-11e8-8312-dd56d4fb1be9.png)

**Comment by themightychris** [comment]
@alexejheroytb you would use Github's [status API ](https://developer.github.com/v3/repos/statuses/) which let's you look up that info for any commit hash

That's a feature of GitHub outside git itself, they don't store that information within the repository

**Comment by Alexejhero** [comment]
Alright, thank you
