### ISSUE TITLE
Could not run js-github in browser

### ISSUE THREAD

**Issue by mquan** [creationix/js-github#6]
I'm using browserify and gulp to build js-github for the browser. The main file, which is copied from the example in the README, is here https://github.com/mquan/git-client/blob/master/src/git.js

It looks like it's partially working because I can `readRef`, but when I run `.loadAs` I see this error

```
Uncaught TypeError: Cannot read property 'transaction' of undefined
```

which is caused by this line in `loadAs` function
```
var trans = db.transaction(["objects"], "readwrite");
```

Do you have any idea why db would be undefined, it seems like I need to add some other require statements.

**Comment by creationix** [comment]
That looks right.  I wonder if your browser doesn't have IndexedDB or if the API changed?  What browser are you testing in exactly?

**Comment by mquan** [comment]
I'm testing it on Chrome 39.0.2171.95, Firefox 32.0.2, Safari 8.0.2 on OSX 10.10.1. They all return the same error message. These are very recent releases and they all list support for indexedDB.

**Comment by mquan** [comment]
I debug some more and found that this `init` function doesn't get called https://github.com/creationix/js-git/blob/4dcd0c53952a42fddfea73281fbf85b963ddb278/mixins/indexed-db.js#L15-L47

When I modify the loadAs code to force init to run then it works. May be this is somehow implicitly called in node env but not in browser?

**Comment by creationix** [comment]
ahh yes.  You need to call init.  The node backends don't need this I think.

**Comment by creationix** [comment]
Should probably improve the error handling somehow and warn if init hasn't been called.

**Comment by mquan** [comment]
Thanks, you may want to update the documentation in README as well. I can successfully commit to github now, but I notice every time `createTree` is called github blob api always returns three 404 errors before succeeding. Is this expected?

**Comment by creationix** [comment]
I remember some of the APIs check github to see if it has certain blobs.
It's unfortunate that 404s always log errors in the browser and there is no
way to suppress it.  I don't remember createTree needing this, but it's
been so long since I worked on this, I might not remember.

**Comment by mquan** [comment]
Thanks a lot for the help. I got js-github mostly working in the browser, will try to find out why those 404s occur.

**Comment by bobby-brennan** [comment]
I just hit this same issue.  Maybe it's worth adding `db.init()` to the README?

**Comment by creationix** [comment]
sounds great, send a PR
